import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../src/components/NavBar";
//import HoneyCombBackground from '../src/components/HoneyCombBackground';
import "./globals.css";

// Google Fonts
/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

// this sets site's title and description in browser tabs and search results
export const metadata: Metadata = {
  title: "JBUNDS PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[#171717] text-amber-50`}
      >
        {/* Background honeycomb pattern - appears on all pages */}
        {/* <HoneyCombBackground /> */}
        
        {/* Main content - positioned above the background */}
        <div className="relative z-10">
          <NavBar />
          <section className='max-w-7xl mx-auto p-12'>
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}

// maybe have cards showing the projects with a hover modal that pops up
// and they can click on the image to go straight to the website, or they
// can click for details and it will automatically route them to the project
// on the project page, and have detials for the projects on the project page
